### ISSUE TITLE
Propagate Error Cases to Client

### ISSUE THREAD

**Issue by camerondurham** [camerondurham/codecanvas#115]
From https://github.com/camerondurham/codecanvas/pull/114#issue-2363051336, there are several cases where we need to propagate errors to client. 

### Criteria of Acceptance

- [ ] program compile time errors are propagated to client
- [ ] program runtime errors are propagated to client in API
- [ ] API response should be JSON de-serializable

### Resources

Code Input Causes Segfault:
```cpp
#include <iostream>

int main() {
    int* nullPtr = nullptr; // Declare a null pointer
    try {
        *nullPtr = 42; // This line will cause a segmentation fault (or access violation on Windows)
        std::cout << "Value at null pointer: " << *nullPtr << std::endl;
    } catch (const std::exception& e) {
        std::cerr << "Exception caught: " << e.what() << std::endl;
    }
    return 0;
}
```

Local Test:
```
g++ test.cpp && ./a.out
zsh: segmentation fault  ./a.out
```

Runner API req/response:

```json
{"source":"#include <iostream>\n\nint main() {\n    int* nullPtr = nullptr; // Declare a null pointer\n\n    // Dereference the null pointer and attempt to access memory at an invalid address\n    try {\n        *nullPtr = 42; // This line will cause a segmentation fault (or access violation on Windows)\n        std::cout << \"Value at null pointer: \" << *nullPtr << std::endl;\n    } catch (const std::exception& e) {\n        std::cerr << \"Exception caught: \" << e.what() << std::endl;\n    }\n\n    return 0;\n}","language":"c++"}

// response
(µ/ýH{"stdout":"","stderr":"","error":{"Stderr":null}}


```

Relevant Logs on Server:
```
2024-06-20T09:25:43.279 app[4d89d054c46e87] lax [info] error copying output: EOFerror copying output: EOF(runCommand) error from running command: exit status 202024/06/20 09:25:43 [4d89d054c46e87/7fsgiRcQs2-000170] "POST http://runner.fly.dev/api/v1/run HTTP/1.1" from 172.16.5.178:41152 - 200 50B in 228.943462ms
```

**Comment by arekouzounian** [comment]
I was looking into how error handling could be improved on the backend, and had some ideas. 

Right now, it looks like whenever a program has an error, like a segfault, most of the data is thrown out in `engine/process/process.go`, and the `ERunningProc` (value of 20) is set as the `process` program's exit code. This seems to be why I was getting the `exit status 20` code on segfaults and other bad programs.

The main issue seems to be that the `process` program can only communicate with the runtime agent via an exit code. A simple solution for error handling could be to check for SIGSEGV, SIGABRT, and other common exit codes, by simply exporting the exit code of the executed command as the exit code of the `process` program. 

A more complicated but possibly more scalable solution to handle errors would be to have the `process` program store the `ExitStatus` of a failed program into some file, which the runtime could read through and then propagate to the frontend accordingly. The only issue is that this would involve more read and write operations on each API call, which could be expensive. 

@camerondurham what are your thoughts on this?

**Comment by camerondurham** [comment]
Nice, thanks for taking a look!

That looks totally right, the context is thrown out/masked in error codes. I definitely prefer propagating the exact exit code of the child process instead of hiding it under a generic "20=something failed".

Code organization wise, I think any "translation" of the exit code could happen in the code running process but ideally no translation at all. Maybe the API response should just return a dedicated exit status field and leave client to figure that out?

**Comment by camerondurham** [comment]
I think this can probably get closed now, thanks again @arekouzounian for the great work implementing this! Was just testing after your latest change deployed and looks like we actually get more feedback from the server for the sample test case:

<img width="741" alt="image" src="https://github.com/camerondurham/codecanvas/assets/17013462/ce9a3aaa-e171-450a-969f-dfe7a7f9fae8">

I think my only concern is about how/why the frontend is parsing the `error` field? 

API response:
```
{"stdout":"","stderr":"signal: segmentation fault","error":"exit status 139"}
```

UI renders:
```
Error: 0: e, 1: x, 2: i, 3: t, 4: , 5: s, 6: t, 7: a, 8: t, 9: u, 10: s, 11: , 12: 1, 13: 3, 14: 9
```
