### ISSUE TITLE
Rename it

### ISSUE THREAD

**Issue by camerondurham** [camerondurham/codecanvas#98]
Chat GPT didn't exist when this was written but it exists now. Use it to come up with a better project name.

https://www.reddit.com/r/golang/comments/16krmxd/comment/k10to73/

Ideas:

1. gobox
2. sandbox
3. codecanvas
4. langbox
5. langpage
6. codefusion (horrible wtf)
7. lang-playground

**Comment by arekouzounian** [comment]
I like "codecanvas", but I'm also partial to alliterative names in general.
